### ISSUE TITLE
intermittent problem with date selection in query screen

### ISSUE THREAD

**Issue by vanatteveldt** [amcat/amcat#499]
In the query screen there is a date-interval selector where you first select the interval (at/between/before/after) and then pick on or two dates. "Sometimes" the selector does not show radio buttons in the dropdown, and in that case the selection also does not work (clicking on one of the options does not show the date pickers, it highlights the selection but doesn't react)

![fout](https://cloud.githubusercontent.com/assets/1736240/14607116/8d7d4344-0580-11e6-86df-299d7bc77b5e.png)

This is how it works when it works:

![goed](https://cloud.githubusercontent.com/assets/1736240/14607115/8d7afc24-0580-11e6-863c-9f44c74ad314.png)

Refreshing solves the problem, but if you keep refreshing it will reappear in 5% of cases or so. It seems that it is more frequent on a clean load than after a refresh, but I'm not sure that even makes sense. 

JS console shows no errors and at first glance the HTML structure from 'inspect' seems identical, so I have no clue what might cause this (but I'm blaming javascript :))

**Comment by markboukes** [comment]
In addition to this: 
When the interval can be selected, the selection does not work properly. Example:

If you selected "on", e.g., 02-06-2015, then you don't get any results. 
If you selected "between", e.g., from 02-06-2015 till 03-06-2015, you only get the results of 02-06-2015.

**Comment by CJStuart** [comment]
Should be fixed now.

**Comment by markboukes** [comment]
Not sure if it is possible to open this again??

The selection on dates still does not work properly.

My explanation before was not correct, here it is again:

If you selected "on", e.g., 02-06-2015, then you **all ** articles instead of the selection based on date. 
If you selected "between", e.g., from 02-06-2015 till 03-06-2015, you only get the results of 02-06-2015.

It works okay for output option "summary" but not for "articlelist", which i need to export the articles.

**Comment by markboukes** [comment]
Hi, my problem is not solved yet. I’ve put extra comments in the forum.

Thanks for the help!
Mark.



______________
Dr. Mark Boukes
Universiteit van Amsterdam / ASCoR
Postbus 15793
Nieuwe Achtergracht  166
1018 WV  Amsterdam, The Netherlands
E-mail: m.boukes@uva.nl<mailto:m.boukes@uva.nl>

**Comment by CJStuart** [comment]
I see, I added a new issue about this.
