### ISSUE TITLE
AUTNES: Amcat-R assertion when querying big article sets

### ISSUE THREAD

**Issue by daevil** [amcat/amcat#692]
When trying to query a big article set ( example: autnes.amcat.nl ; project: 3 ; set: 3237 ) it returns an empty table and I get the following error message:

Warning messages:
1: Unknown or uninitialised column: 'id'. 
2: Unknown or uninitialised column: 'id'. 
3: In value[[3L]](cond) :
Error on querying 'query1': Unexpected Response Code 500
This seems to be an AmCAT server error. Please see the server logs or create an issue at http://github.com/amcat/amcat/issues
TransportError: TransportError(500, 'search_phase_execution_exception', 'Result window is too large, from + size must be less than or equal to: [10000] but was [11000]. See the scroll api for a more efficient way to request large data sets. This limit can be set by changing the [index.max_result_window] index level setting.')

To reproduce this is the code I used:
require(amcatr)
conn <- amcat.connect("http://autnes.amcat.nl")

query1 <- 'deutschland# (merkel* OR seehofer OR weidel OR gauland OR petry OR "simone peter" OR söder OR lindner OR özdemir OR schulz OR nahles OR spd OR cdu OR csu OR fdp OR afd OR bundestagswahl) NOT (nationalrat* OR spö* OR övp* OR "liste kurz"~4 OR "neue* volkspartei" OR fpö* OR neos* OR "liste pilz"~4 OR "kurz övp"~5 OR "sebastian kurz"~4 OR "minister kurz"~5 OR "bundesminister* kurz"~5 OR "europa* kurz"~5 OR "integration* kurz"~5 OR "außenminister* kurz"~5 OR "äußeres* kurz"~5 OR "kurz volkspartei"~5 OR "kurz vp"~5 OR "kanzler* kern"~5 "bundeskanzler* kern"~5 "christian kern"~4 "kern spö"~5 "kern sozialdemokrat*"~5 OR "minister* stöger"~5 OR "bundesminister* stöger"~5 OR "gesundheit* stöger"~5 OR "sozial* stöger"~5 "arbeit* stöger"~5 OR "alois stöger"~4 OR "brandstetter minister*"~5 OR "bundesminister* brandstetter"~5  OR "wolfgang brandstetter"~4 OR "justiz* brandstetter"~5 OR doskozil OR drozda OR "minister* hammerschmid"~5 OR "bundesminister* hammerschmid"~5 OR "bildung* hammerschmid"~5 OR "sonja hammerschmid"~4 OR karmasin OR "leichtfried minister*"~5 OR "verkehrsminister* leichtfried"~5 "jörg leichtfried"~4 OR "minister* mahrer"~5 OR "bundesminister* mahrer"~5 OR "wirtschaft* mahrer"~5 OR "wissenschaft* mahrer"~5 OR "forschung* mahrer"~6 OR "staatssekretär* mahrer"~5 OR "harald mahrer"~4 OR "minister* rendi-wagner"~5 OR "minister* wagner"~5 OR "bundesminister* rendi-wagner"~5 OR "bundesminister* wagner"~5 OR "gesundheitsminister* wagner"~5 OR "gesundheitsminister* rendi-wagner"~5 OR "frauenminister* wagner"~5 OR "frauenminister* rendi-wagner"~5 OR "pamela rendi-wagner"~5 OR "rendi wagner"~5 OR "minister* rupprechter"~5 OR "andrä rupprechter"~4 OR "landwirtschaftsminister* rupprechter"~5 OR "umweltminister* rupprechter"~5 OR "minister* schelling"~5 OR "finanzminister* schelling"~5 OR "hans-jörg schelling"~4 "hans jörg schelling" OR "johann georg schelling" OR ("minister* sobotka"~5 NOT tschechi*) OR "innenminister* sobotka"~5 OR "wolfgang sobotka"~4 OR "van der bellen" OR bundespräsident OR strache* OR "matthias strolz"~4 OR "neos* strolz"~6 OR lunacek OR "peter pilz"~4 OR "ex-grün* pilz"~6 OR "grüne* pilz"~6 OR "politiker* pilz"~5 OR "aufdecker* pilz"~5 OR "untersuchung* pilz"~5 OR "abgeordnete* pilz"~5 "parlament* pilz"~5 OR lunacek OR "tiroler grüne*" OR "grüne* tirol" OR "wiener grüne*" OR "grüne* wien" OR "grüne* burgenland" OR "burgenländ* grüne*" OR "grüne* kärnten" OR "kärntner* grüne*" OR "grüne* salzburg" OR "salzburger* grüne*" OR "grüne* oberösterreich" OR "oberösterreichische* grüne*" OR "grüne* steiermark" OR "steirische* grüne*" OR "grüne* vorarlberg" OR "vorarlberger grüne*" OR "grüne* niederösterreich*" OR "niederösterreichische* grüne*")'
query2 <- 'der'

setname1 <- 'deutschland wahl'
setname2 <- 'liste pilz iteration 2'
diffsetname <-'liste pilz diff set'

#saving results to new set...
# querying for query 1
h1 <- amcat.hits(conn, project = 3, sets = 3237,
                 queries = query1, labels = 'query1')

#this is where it breaks. a also used a much shorter search string to check if that was the issue. didn't work either

Thanks in advance!
Best regards, Gregor

**Comment by vanatteveldt** [comment]
Confirmed the error, probably the query is too long for a GET request. Server log says:

```
invalid request block size: 8934 (max 4096)...skip
```

**Comment by daevil** [comment]
This laos happens when you replace the long query1 string with 'der'. 

So it can't be just that.

**Comment by vanatteveldt** [comment]
This error is fixed, I set the buffer size to 32k - maybe you queried right while I was resetting the server? 

(btw it gives no result, if that is unexpected, try again without the accents, it should strip them anyway?)

**Comment by daevil** [comment]
Unfortunatly the issue still remains. 

To reproduce try this code with a much simpler query:

require(amcatr)
conn <- amcat.connect("http://autnes.amcat.nl")
query2 <- 'der'
h1 <- amcat.hits(conn, project = 3, sets = 3237,
                 queries = query2, labels = 'query1')

still results in:

Warning message:
In value[[3L]](cond) :
  Error on querying 'query1': Unexpected Response Code 500
This seems to be an AmCAT server error. Please see the server logs or create an issue at http://github.com/amcat/amcat/issues
TransportError: TransportError(500, 'search_phase_execution_exception', 'Result window is too large, from + size must be less than or equal to: [10000] but was [11000]. See the scroll api for a more efficient way to request large data sets. This limit can be set by changing the [index.max_result_window] index level setting.')

**Comment by vanatteveldt** [comment]
This is actually a different error, I created a new issue at #693
